#!/usr/bin/env python3
"""Regenerate res/values/ids.xml from the id-like string literals in the scenario code.

Scenario views get real resource ids (so the a11y tree reports viewIdResourceName)
through Sc.rid(name), which fails loudly if a name is missing here. Over-inclusion
is harmless. Run after adding a scenario: python3 android/testapp/gen_ids.py
"""
import keyword
import pathlib
import re

# Java keywords cannot be resource names (the scenario code must not use them as ids)
JAVA_KEYWORDS = set("abstract assert boolean break byte case catch char class const continue default do double else enum extends final finally float for goto if implements import instanceof int interface long native new package private protected public return short static strictfp super switch synchronized this throw throws transient try void volatile while true false null".split())

here = pathlib.Path(__file__).resolve().parent
src = here / "src/main/java/dev/droidctl/testapp"
names = set()
for f in src.glob("*.kt"):
    names |= set(re.findall(r'"([a-z][a-z0-9_]*)"', f.read_text()))
# RecyclerViews built by G3.recycler get "<id>_list"
names |= {n + "_list" for n in ("note", "row", "item", "entry", "post", "contact")}
# ids built from templates in the code ("key_$it", "otp$i")
names |= {f"key_{d}" for d in range(10)} | {f"otp{i}" for i in range(1, 7)}
names -= JAVA_KEYWORDS
body = "\n".join(f'    <item type="id" name="{n}" />' for n in sorted(names))
out = here / "src/main/res/values/ids.xml"
out.write_text(f'<?xml version="1.0" encoding="utf-8"?>\n<!-- generated by gen_ids.py -->\n<resources>\n{body}\n</resources>\n')
print(f"{len(names)} ids -> {out}")
